version: "3.8"

services:

    web:
        image: nginx:mainline
        ports:
            - '8080:80'
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm

    php-fpm:
        build:
            dockerfile: ".docker/Dockerfile_api"
            context: "."
        volumes:
            - ./src:/var/www/html
        depends_on:
            - kafka
            - database

    database:
        image: postgres:12.18-bullseye
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: dev
            POSTGRES_USER: dev
            POSTGRES_DB: api

    kafka:
        image: bitnami/kafka:3.6
        ports:
            - "9094:9094"
        environment:
        - KAFKA_CFG_NODE_ID=0
        - KAFKA_CFG_PROCESS_ROLES=controller,broker
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@<your_host>:9093
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

    worker:
        restart: always
        build:
            dockerfile: ".docker/Dockerfile_worker"
            context: "."
        volumes:
            - ./src:/var/www/html
        depends_on:
            - kafka
            - database
