
#Ideally this will be inherited from a commom image, duplicating part of the definition for simplicity
FROM php:8.3-fpm

RUN apt update

#install zip extension
RUN apt install libzip-dev -y
RUN docker-php-ext-install zip && docker-php-ext-configure zip

#install pgsql extension
RUN apt-get install -y libpq-dev \
        && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
        && docker-php-ext-install pdo pdo_pgsql pgsql

#install kafka extension
RUN apt-get install librdkafka-dev -y
RUN pecl install rdkafka \
    && docker-php-ext-enable rdkafka

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

COPY ./src /var/www/html

RUN chown www-data -R storage/ -R
